# Generated by Django 4.2.14 on 2024-07-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='calories',
            new_name='calories_Per_Serving',
        ),
    ]
