# Generated by Django 4.2.14 on 2024-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_calories_recipe_calories_per_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=0),
        ),
    ]
