# Generated by Django 4.2.14 on 2024-08-02 15:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredient_remove_recipe_calories_per_serving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_alt',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
