# Generated by Django 4.2.14 on 2024-08-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_category_remove_recipe_meal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetisers', 'Appetizers'), ('beverages', 'Beverages'), ('soups', 'Soups'), ('salads', 'Salads'), ('vegan', 'Vegan'), ('vegeterian', 'Vegeterian'), ('main dishes', 'Main Dishes'), ('desserts', 'Desserts')], default='main dishes', max_length=50),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
