# Generated by Django 4.2.14 on 2024-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetisers/snacks', 'Appetizers/Snacks'), ('beverages', 'Beverages'), ('soups', 'Soups'), ('salads', 'Salads'), ('main dishes', 'Main Dishes'), ('desserts', 'Desserts')], default='main dishes', max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
